version: "3.9"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:80"  # host:container
    command: ["./bin/thrust", "./bin/rails", "server", "-b", "0.0.0.0"]
    volumes:
      - ./backend:/rails
    environment:
      RAILS_ENV: development
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    command: ["npm", "run", "dev", "--", "--host"]